import { ResumeTemplate } from "./types";

export const templates: ResumeTemplate[] = [
  {
    id: "ats-classic",
    name: "ATS Classic",
    description: "Centered header, thin rules, no photo — built to pass scanners.",
    layout: "centered-classic",
    accent: "#1B1F29",
    accentSoft: "#EDEFF3",
    headingFont: "serif",
    bestFor: "Corporate, IT, and ATS-heavy applications",
  },
  {
    id: "clean-list",
    name: "Clean List",
    description: "Gray section bars with diamond bullets, no photo.",
    layout: "banner-headers",
    accent: "#4A4A4A",
    accentSoft: "#E9E9E9",
    headingFont: "sans",
    bestFor: "Logistics, analyst, and back-office roles",
  },
  {
    id: "emerald-sidebar",
    name: "Emerald Sidebar",
    description: "Dark green left sidebar with circular photo and skill bars.",
    layout: "sidebar-left-dark",
    accent: "#0F3D2E",
    accentSoft: "#DCEAE3",
    headingFont: "sans",
    bestFor: "Customer service and hospitality roles",
  },
  {
    id: "blue-header",
    name: "Blue Header",
    description: "Bold blue name with a square photo top-right.",
    layout: "photo-top-header",
    accent: "#1550C9",
    accentSoft: "#EAF1FE",
    headingFont: "sans",
    bestFor: "Finance, analyst, and corporate roles",
  },
  {
    id: "navy-sidebar",
    name: "Navy Sidebar",
    description: "Deep navy sidebar on the right with rounded skill tags.",
    layout: "sidebar-right-dark",
    accent: "#0B2545",
    accentSoft: "#D9E2EF",
    headingFont: "sans",
    bestFor: "Skilled trades and technical roles",
  },
  {
    id: "sage-minimal",
    name: "Sage Minimal",
    description: "Soft sage header block with minimal, airy sections.",
    layout: "block-header-single",
    accent: "#6E8B5D",
    accentSoft: "#EAF0E3",
    headingFont: "sans",
    bestFor: "Bookkeeping, admin, and clerical roles",
  },
  {
    id: "soft-sidebar",
    name: "Soft Sidebar",
    description: "Light gray sidebar on the right with a circular photo.",
    layout: "sidebar-right-light",
    accent: "#3E63DD",
    accentSoft: "#EEF1FB",
    headingFont: "sans",
    bestFor: "Finance and analyst roles that want a photo",
  },
  {
    id: "bold-blocks",
    name: "Bold Blocks",
    description: "Large name, square photo, and full-width black section bars.",
    layout: "block-photo-header",
    accent: "#111111",
    accentSoft: "#F2F2F2",
    headingFont: "sans",
    bestFor: "Healthcare, psychology, and clinical roles",
  },
  {
    id: "ph-formal",
    name: "PH Formal Application",
    description: "Bordered ID-photo layout with full personal details — the classic Filipino application format.",
    layout: "formal-ph",
    accent: "#8C7A6B",
    accentSoft: "#EFE7E1",
    headingFont: "sans",
    bestFor: "Entry-level and walk-in job applications",
  },
  {
    id: "burgundy-executive",
    name: "Burgundy Executive",
    description: "A polished, centered design with refined rules and traditional typography.",
    layout: "centered-classic",
    accent: "#7A263A",
    accentSoft: "#F5E9EC",
    headingFont: "serif",
    bestFor: "Management, legal, and executive applications",
  },
  {
    id: "teal-professional",
    name: "Teal Professional",
    description: "Crisp information bars and a calming teal accent for easy scanning.",
    layout: "banner-headers",
    accent: "#116466",
    accentSoft: "#E3F1F0",
    headingFont: "sans",
    bestFor: "Operations, project, and business roles",
  },
  {
    id: "plum-portfolio",
    name: "Plum Portfolio",
    description: "A creative left-sidebar layout that gives your profile photo room to stand out.",
    layout: "sidebar-left-dark",
    accent: "#4B315E",
    accentSoft: "#EDE6F2",
    headingFont: "sans",
    bestFor: "Creative, marketing, and portfolio-led roles",
  },
  {
    id: "skyline",
    name: "Skyline",
    description: "A modern blue header with a clean photo-led introduction.",
    layout: "photo-top-header",
    accent: "#1976B9",
    accentSoft: "#E7F3FB",
    headingFont: "sans",
    bestFor: "Technology, consulting, and graduate applications",
  },
  {
    id: "charcoal-craft",
    name: "Charcoal Craft",
    description: "Strong dark sidebar and compact detail treatment for practical experience.",
    layout: "sidebar-right-dark",
    accent: "#30343B",
    accentSoft: "#E8EAED",
    headingFont: "mono",
    bestFor: "Technical, skilled trade, and engineering roles",
  },
  {
    id: "rosewood-minimal",
    name: "Rosewood Minimal",
    description: "A warm, spacious header that keeps essential information beautifully focused.",
    layout: "block-header-single",
    accent: "#9A4D5A",
    accentSoft: "#F8EBED",
    headingFont: "sans",
    bestFor: "Education, administration, and people-focused roles",
  },
];

export const getTemplate = (id: string): ResumeTemplate =>
  templates.find((t) => t.id === id) ?? templates[0];
