import { ResumeTemplate } from "./types";

export const templates: ResumeTemplate[] = [
  {
    id: "ats-classic",
    name: "ATS Classic",
    description: "Centered header, thin rules, no photo — built to pass scanners.",
    layout: "centered-classic",
    accent: "#1B1F29",
    accentSoft: "#EDEFF3",
    headingFont: "serif",
    bestFor: "Corporate, IT, and ATS-heavy applications",
  },
  {
    id: "clean-list",
    name: "Clean List",
    description: "Gray section bars with diamond bullets, no photo.",
    layout: "banner-headers",
    accent: "#4A4A4A",
    accentSoft: "#E9E9E9",
    headingFont: "sans",
    bestFor: "Logistics, analyst, and back-office roles",
  },
  {
    id: "emerald-sidebar",
    name: "Emerald Sidebar",
    description: "Dark green left sidebar with circular photo and skill bars.",
    layout: "sidebar-left-dark",
    accent: "#0F3D2E",
    accentSoft: "#DCEAE3",
    headingFont: "sans",
    bestFor: "Customer service and hospitality roles",
  },
  {
    id: "blue-header",
    name: "Blue Header",
    description: "Bold blue name with a square photo top-right.",
    layout: "photo-top-header",
    accent: "#1550C9",
    accentSoft: "#EAF1FE",
    headingFont: "sans",
    bestFor: "Finance, analyst, and corporate roles",
  },
  {
    id: "navy-sidebar",
    name: "Navy Sidebar",
    description: "Deep navy sidebar on the right with rounded skill tags.",
    layout: "sidebar-right-dark",
    accent: "#0B2545",
    accentSoft: "#D9E2EF",
    headingFont: "sans",
    bestFor: "Skilled trades and technical roles",
  },
  {
    id: "sage-minimal",
    name: "Sage Minimal",
    description: "Soft sage header block with minimal, airy sections.",
    layout: "block-header-single",
    accent: "#6E8B5D",
    accentSoft: "#EAF0E3",
    headingFont: "sans",
    bestFor: "Bookkeeping, admin, and clerical roles",
  },
  {
    id: "soft-sidebar",
    name: "Soft Sidebar",
    description: "Light gray sidebar on the right with a circular photo.",
    layout: "sidebar-right-light",
    accent: "#3E63DD",
    accentSoft: "#EEF1FB",
    headingFont: "sans",
    bestFor: "Finance and analyst roles that want a photo",
  },
  {
    id: "bold-blocks",
    name: "Bold Blocks",
    description: "Large name, square photo, and full-width black section bars.",
    layout: "block-photo-header",
    accent: "#111111",
    accentSoft: "#F2F2F2",
    headingFont: "sans",
    bestFor: "Healthcare, psychology, and clinical roles",
  },
  {
    id: "ph-formal",
    name: "PH Formal Application",
    description: "Bordered ID-photo layout with full personal details — the classic Filipino application format.",
    layout: "formal-ph",
    accent: "#8C7A6B",
    accentSoft: "#EFE7E1",
    headingFont: "sans",
    bestFor: "Entry-level and walk-in job applications",
  },
];

export const getTemplate = (id: string): ResumeTemplate =>
  templates.find((t) => t.id === id) ?? templates[0];
